GET http://localhost:3900/user-api/get-user
###
GET http://localhost:3900/user-api/get-user/100
###
POST http://localhost:3900/user-api/create-user
Content-Type: application/json

{
    "id":100,
    "name":"sathvik",
    "age":19
}
###
PUT http://localhost:3700/update-user
Content-Type: application/json

{
    "id":100,
    "name":"sunny",
    "age":19
}
###
DELETE http://localhost:3900/product-api/delete-product/200
###
GET http://localhost:3900/product-api/get-product
###
POST http://localhost:3900/product-api/create-product
###
PUT http://localhost:3900/product-api/update-product
###
GET http://localhost:3900/product-api/get-product/100
###
###